part of 'kimmi_ernie_asthmatic.dart';

class KimmiErnieAsthmaticDecode extends _KimmiErnieAsthmaticDecode {
  const KimmiErnieAsthmaticDecode({required super.args});

  static const kType = 'kimmi_ernie_asthmatic';

  @override
  String get type => kType;

  static KimmiErnieAsthmaticDecode fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      KimmiErnieAsthmaticDecode(
        args: map,
      );

  @override
  KimmiErnieAsthmaticDecodeStorm createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = KimmiErnieAsthmaticDecodeStorm.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  KimmiErnieAsthmatic buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );

    return KimmiErnieAsthmatic(
      borderRadius: model.borderRadius,
      color: model.color,
      fit: model.fit,
      height: model.height,
      key: key,
      onTap: model.onTap,
      url: model.url,
      width: model.width,
    );
  }
}

class JsonKimmiErnieAsthmatic extends JsonWidgetData {
  JsonKimmiErnieAsthmatic({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.borderRadius,
    this.color = Colors.transparent,
    this.fit = BoxFit.contain,
    this.height,
    this.onTap,
    required this.url,
    this.width,
  }) : super(
          jsonWidgetArgs: KimmiErnieAsthmaticDecodeStorm.fromDynamic(
            {
              'borderRadius': borderRadius,
              'color': color,
              'fit': fit,
              'height': height,
              'onTap': onTap,
              'url': url,
              'width': width,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => KimmiErnieAsthmaticDecode(
            args: KimmiErnieAsthmaticDecodeStorm.fromDynamic(
              {
                'borderRadius': borderRadius,
                'color': color,
                'fit': fit,
                'height': height,
                'onTap': onTap,
                'url': url,
                'width': width,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: KimmiErnieAsthmaticDecode.kType,
        );

  final BorderRadius? borderRadius;

  final Color? color;

  final BoxFit? fit;

  final double? height;

  final void Function()? onTap;

  final String url;

  final double? width;
}

/* AUTOGENERATED FROM [KimmiErnieAsthmatic]*/
class KimmiErnieAsthmaticDecodeStorm extends JsonWidgetBuilderModel {
  const KimmiErnieAsthmaticDecodeStorm(
    super.args, {
    this.borderRadius,
    this.color = Colors.transparent,
    this.fit = BoxFit.contain,
    this.height,
    this.onTap,
    required this.url,
    this.width,
  });

  final BorderRadius? borderRadius;

  final Color? color;

  final BoxFit? fit;

  final double? height;

  final void Function()? onTap;

  final String url;

  final double? width;

  static KimmiErnieAsthmaticDecodeStorm fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );

    if (result == null) {
      throw Exception(
        '[KimmiErnieAsthmaticDecode]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static KimmiErnieAsthmaticDecodeStorm? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    KimmiErnieAsthmaticDecodeStorm? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }

      if (map is KimmiErnieAsthmaticDecodeStorm) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = KimmiErnieAsthmaticDecodeStorm(
          args,
          borderRadius: () {
            dynamic parsed = ThemeDecoder.decodeBorderRadius(
              map['borderRadius'],
              validate: false,
            );

            return parsed;
          }(),
          color: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['color'],
              validate: false,
            );
            if (!map.containsKey('color')) {
              parsed ??= Colors.transparent;
            }

            return parsed;
          }(),
          fit: () {
            dynamic parsed = ThemeDecoder.decodeBoxFit(
              map['fit'],
              validate: false,
            );
            if (!map.containsKey('fit')) {
              parsed ??= BoxFit.contain;
            }

            return parsed;
          }(),
          height: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['height']);

            return parsed;
          }(),
          onTap: map['onTap'],
          url: map['url'],
          width: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['width']);

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'borderRadius': ThemeEncoder.encodeBorderRadius(
        borderRadius,
      ),
      'color': Colors.transparent == color
          ? null
          : ThemeEncoder.encodeColor(
              color,
            ),
      'fit': BoxFit.contain == fit
          ? null
          : ThemeEncoder.encodeBoxFit(
              fit,
            ),
      'height': height,
      'onTap': onTap,
      'url': url,
      'width': width,
      ...args,
    });
  }
}

class KimmiErnieAsthmaticMobster {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/kimmi/kimmi_ernie_asthmatic.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'KimmiErnieAsthmatic',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'borderRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'color': SchemaHelper.objectSchema(ColorSchema.id),
      'fit': SchemaHelper.objectSchema(BoxFitSchema.id),
      'height': SchemaHelper.numberSchema,
      'onTap': SchemaHelper.anySchema,
      'url': SchemaHelper.stringSchema,
      'width': SchemaHelper.numberSchema,
    },
  };
}
