part of 'kimmi_yummy_asthmatic.dart';

class KimmiYummyAsthmaticDecode extends _KimmiYummyAsthmaticDecode {
  const KimmiYummyAsthmaticDecode({required super.args});

  static const kType = 'kimmi_yummy_asthmatic';

  @override
  String get type => kType;

  static KimmiYummyAsthmaticDecode fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      KimmiYummyAsthmaticDecode(
        args: map,
      );

  @override
  KimmiYummyAsthmaticDecodeStorm createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = KimmiYummyAsthmaticDecodeStorm.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  KimmiYummyAsthmatic buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );

    return KimmiYummyAsthmatic(
      borderRadius: model.borderRadius,
      colorFrom: model.colorFrom,
      colorTo: model.colorTo,
      height: model.height,
      key: key,
      onTap: model.onTap,
      title: model.title,
      titleColor: model.titleColor,
      titleFontSize: model.titleFontSize,
      titleFontWeight: model.titleFontWeight,
      width: model.width,
    );
  }
}

class JsonKimmiYummyAsthmatic extends JsonWidgetData {
  JsonKimmiYummyAsthmatic({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.borderRadius,
    this.colorFrom = const Color.fromRGBO(247, 92, 255, 1),
    this.colorTo = const Color.fromRGBO(68, 176, 243, 1),
    required this.height,
    required this.onTap,
    required this.title,
    this.titleColor = Colors.white,
    this.titleFontSize = 16,
    this.titleFontWeight = FontWeight.bold,
    required this.width,
  }) : super(
          jsonWidgetArgs: KimmiYummyAsthmaticDecodeStorm.fromDynamic(
            {
              'borderRadius': borderRadius,
              'colorFrom': colorFrom,
              'colorTo': colorTo,
              'height': height,
              'onTap': onTap,
              'title': title,
              'titleColor': titleColor,
              'titleFontSize': titleFontSize,
              'titleFontWeight': titleFontWeight,
              'width': width,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => KimmiYummyAsthmaticDecode(
            args: KimmiYummyAsthmaticDecodeStorm.fromDynamic(
              {
                'borderRadius': borderRadius,
                'colorFrom': colorFrom,
                'colorTo': colorTo,
                'height': height,
                'onTap': onTap,
                'title': title,
                'titleColor': titleColor,
                'titleFontSize': titleFontSize,
                'titleFontWeight': titleFontWeight,
                'width': width,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: KimmiYummyAsthmaticDecode.kType,
        );

  final BorderRadius? borderRadius;

  final Color colorFrom;

  final Color colorTo;

  final double height;

  final void Function()? onTap;

  final String title;

  final Color titleColor;

  final double? titleFontSize;

  final FontWeight? titleFontWeight;

  final double width;
}

/* AUTOGENERATED FROM [KimmiYummyAsthmatic]*/
class KimmiYummyAsthmaticDecodeStorm extends JsonWidgetBuilderModel {
  const KimmiYummyAsthmaticDecodeStorm(
    super.args, {
    this.borderRadius,
    this.colorFrom = const Color.fromRGBO(247, 92, 255, 1),
    this.colorTo = const Color.fromRGBO(68, 176, 243, 1),
    required this.height,
    required this.onTap,
    required this.title,
    this.titleColor = Colors.white,
    this.titleFontSize = 16,
    this.titleFontWeight = FontWeight.bold,
    required this.width,
  });

  final BorderRadius? borderRadius;

  final Color colorFrom;

  final Color colorTo;

  final double height;

  final void Function()? onTap;

  final String title;

  final Color titleColor;

  final double? titleFontSize;

  final FontWeight? titleFontWeight;

  final double width;

  static KimmiYummyAsthmaticDecodeStorm fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );

    if (result == null) {
      throw Exception(
        '[KimmiYummyAsthmaticDecode]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static KimmiYummyAsthmaticDecodeStorm? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    KimmiYummyAsthmaticDecodeStorm? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }

      if (map is KimmiYummyAsthmaticDecodeStorm) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = KimmiYummyAsthmaticDecodeStorm(
          args,
          borderRadius: () {
            dynamic parsed = ThemeDecoder.decodeBorderRadius(
              map['borderRadius'],
              validate: false,
            );

            return parsed;
          }(),
          colorFrom: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['colorFrom'],
              validate: false,
            );
            parsed ??= const Color.fromRGBO(247, 92, 255, 1);

            return parsed;
          }(),
          colorTo: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['colorTo'],
              validate: false,
            );
            parsed ??= const Color.fromRGBO(68, 176, 243, 1);

            return parsed;
          }(),
          height: () {
            dynamic parsed = JsonClass.parseDouble(map['height']);

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [height].',
              );
            }
            return parsed;
          }(),
          onTap: map['onTap'],
          title: map['title'],
          titleColor: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['titleColor'],
              validate: false,
            );
            parsed ??= Colors.white;

            return parsed;
          }(),
          titleFontSize: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['titleFontSize']);

            if (!map.containsKey('titleFontSize')) {
              parsed ??= 16.0;
            }

            return parsed;
          }(),
          titleFontWeight: () {
            dynamic parsed = ThemeDecoder.decodeFontWeight(
              map['titleFontWeight'],
              validate: false,
            );
            if (!map.containsKey('titleFontWeight')) {
              parsed ??= FontWeight.bold;
            }

            return parsed;
          }(),
          width: () {
            dynamic parsed = JsonClass.parseDouble(map['width']);

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [width].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'borderRadius': ThemeEncoder.encodeBorderRadius(
        borderRadius,
      ),
      'colorFrom': const Color.fromRGBO(247, 92, 255, 1) == colorFrom
          ? null
          : ThemeEncoder.encodeColor(
              colorFrom,
            ),
      'colorTo': const Color.fromRGBO(68, 176, 243, 1) == colorTo
          ? null
          : ThemeEncoder.encodeColor(
              colorTo,
            ),
      'height': height,
      'onTap': onTap,
      'title': title,
      'titleColor': Colors.white == titleColor
          ? null
          : ThemeEncoder.encodeColor(
              titleColor,
            ),
      'titleFontSize': 16 == titleFontSize ? null : titleFontSize,
      'titleFontWeight': FontWeight.bold == titleFontWeight
          ? null
          : ThemeEncoder.encodeFontWeight(
              titleFontWeight,
            ),
      'width': width,
      ...args,
    });
  }
}

class KimmiYummyAsthmaticMobster {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/kimmi/kimmi_yummy_asthmatic.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'KimmiYummyAsthmatic',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'borderRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'colorFrom': SchemaHelper.objectSchema(ColorSchema.id),
      'colorTo': SchemaHelper.objectSchema(ColorSchema.id),
      'height': SchemaHelper.numberSchema,
      'onTap': SchemaHelper.anySchema,
      'title': SchemaHelper.stringSchema,
      'titleColor': SchemaHelper.objectSchema(ColorSchema.id),
      'titleFontSize': SchemaHelper.numberSchema,
      'titleFontWeight': SchemaHelper.objectSchema(FontWeightSchema.id),
      'width': SchemaHelper.numberSchema,
    },
  };
}
